const DETAILS_RECEIVED = "DETAILS_RECEIVED";
const DETAILS_CLEAR = "DETAILS_CLEAR";
const DETAILS_HISTORY = "DETAILS_HISTORY";

export default {
    DETAILS_RECEIVED,
    DETAILS_CLEAR,
    DETAILS_HISTORY,
};
