const FAVORITES_ADD = "FAVORITES_ADD";
const FAVORITES_REMOVE = "FAVORITES_REMOVE";
const FAVORITES_APPEND = "FAVORITES_APPEND";
const FAVORITES_UPDATE = "FAVORITES_UPDATE";
const FAVORITES_ACTUALIZE = "FAVORITES_ACTUALIZE";
const FAVORITES_CLEAR = "FAVORITES_CLEAR";

export default {
    FAVORITES_ADD,
    FAVORITES_REMOVE,
    FAVORITES_APPEND,
    FAVORITES_UPDATE,
    FAVORITES_ACTUALIZE,
    FAVORITES_CLEAR,
};

export const favoritesKeys = {
    ids: "favorites_ids",
    values: "favorites_values",
};
